# Netlify Configuration for Lucaverse Security Headers
[build]
  publish = "dist"
  command = "npm run build"

# Security Headers Configuration
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - Secure without unsafe directives
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' https://accounts.google.com https://apis.google.com;
      style-src 'self' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://summer-heart.lucianoaf8.workers.dev https://lucaverse-auth.lucianoaf8.workers.dev https://formerformfarmer.lucianoaf8.workers.dev https://accounts.google.com https://oauth2.googleapis.com https://www.googleapis.com;
      frame-src 'self' https://accounts.google.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://summer-heart.lucianoaf8.workers.dev https://lucaverse-auth.lucianoaf8.workers.dev https://formerformfarmer.lucianoaf8.workers.dev;
      frame-ancestors 'none';
      upgrade-insecure-requests;
    '''
    
    # Prevent clickjacking attacks
    X-Frame-Options = "DENY"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # XSS protection (legacy but still useful)
    X-XSS-Protection = "1; mode=block"
    
    # Force HTTPS connections
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Control browser permissions
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), accelerometer=(), gyroscope=(), magnetometer=()"
    
    # Additional security headers
    X-DNS-Prefetch-Control = "off"
    X-Permitted-Cross-Domain-Policies = "none"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"

# Static assets caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Font caching
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Redirect configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security-focused build settings
[build.environment]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"