name: 'Monitor Cloudflare Pages Build'
description: 'Monitors Cloudflare Pages deployment status with detailed logging'
inputs:
  account-id:
    description: 'Cloudflare Account ID'
    required: true
  project-name:
    description: 'Cloudflare Pages Project Name'
    required: true
  api-token:
    description: 'Cloudflare API Token'
    required: true
  max-wait-minutes:
    description: 'Maximum wait time in minutes'
    required: false
    default: '10'
  poll-interval-seconds:
    description: 'Polling interval in seconds'
    required: false
    default: '30'

outputs:
  deployment-status:
    description: 'Final deployment status (success/failure)'
    value: ${{ steps.monitor.outputs.status }}
  deployment-url:
    description: 'Deployment URL if successful'
    value: ${{ steps.monitor.outputs.url }}
  deployment-id:
    description: 'Cloudflare deployment ID'
    value: ${{ steps.monitor.outputs.deployment-id }}

runs:
  using: 'node20'
  main: 'monitor.js'